(define (problem redflix) (:domain practica_Redflix_1)
(:objects 
p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 p12 - pelicula
universo1 universo2 universo3 universo4 - universo
d1 d2 d3 d4 d5 d6 d7 d8 d9 d10 d11 d12 - dia
)

(:init
    (= (ContPorVer) 3)
    (diaActual d1)
    (siguienteDia d1 d2)
    (siguienteDia d2 d3)
    (siguienteDia d3 d4)
    (siguienteDia d4 d5)
    (siguienteDia d5 d6)
    (siguienteDia d6 d7)
    (siguienteDia d7 d8)
    (siguienteDia d8 d9)
    (siguienteDia d9 d10)
    (siguienteDia d10 d11)
    (siguienteDia d11 d12)
    (EnCatalogo p1)
    (EnCatalogo p2)
    (EnCatalogo p3)
    (EnCatalogo p4)
    (EnCatalogo p5)
    (EnCatalogo p6)
    (EnCatalogo p7)
    (EnCatalogo p8)
    (EnCatalogo p9)
    (EnCatalogo p10)
    (EnCatalogo p11)
    (EnCatalogo p12)
    (quererVer p1)
    (quererVer p5)
    (quererVer p4)
    (predecesor p2 p6 universo1)
    (predecesor p6 p10 universo1)
    (predecesor p1 p7 universo2)
    (predecesor p7 p9 universo2)
    (predecesor p3 p8 universo3)
    (predecesor p8 p11 universo3)
    (predecesor p4 p5 universo4)
    (predecesor p5 p12 universo4)
    (ContInicial p1 universo2)
    (ContInicial p2 universo1)
    (ContInicial p3 universo3)
    (ContInicial p4 universo4)
)

(:goal
    (and (= (ContPorVer) 0))
)

)